# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noleggi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noleggio',
            old_name='fkAuto',
            new_name='fkauto',
        ),
        migrations.AddField(
            model_name='auto',
            name='immagine',
            field=models.ImageField(null=True, upload_to='staticfiles/images/auto'),
        ),
    ]
