# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 15:23
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noleggi', '0003_auto_20160429_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='miniatura',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=''),
        ),
    ]
