# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noleggi', '0004_auto_miniatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='miniatura',
        ),
    ]
